language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e "
        using Pkg
        Pkg.clone(pwd(), \"Chain\");
        Pkg.build(\"Chain\");
        Pkg.test(\"Chain\"; coverage=true)
      "
after_success:
  - julia -e 'cd(Pkg.dir("Chain")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

